/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Contact: typeof import('./src/components/Contact.vue')['default']
    DataCell: typeof import('./src/components/DataCell.vue')['default']
    DataTableColumn: typeof import('./src/components/DataTableColumn.vue')['default']
    ErrorMessage: typeof import('./src/components/ErrorMessage.vue')['default']
    FileUploadField: typeof import('./src/components/FileUploadField.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    Listbox: typeof import('primevue/listbox')['default']
    Message: typeof import('primevue/message')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
